package com.rkktt.taskmaster;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "taskinfo")
public class TaskInfo {
    private String id;
    private String title;
    private String desc;
    private String status;

    public TaskInfo(){};

    public TaskInfo(String title, String desc, String status) {
        this.title = title;
        this.desc = desc;
        this.status = status;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute
    public String getDesc() {
        return desc;
    }

    public void setStatus(String msrp) {
        this.status = status;
    }


}
